# Generated by Django 5.0.4 on 2024-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='RandomQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
