# Generated by Django 5.0.6 on 2024-05-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TLQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('timeLimit', models.IntegerField(default=10)),
            ],
        ),
    ]
